spring:
  config:
    activate:
      on-profile: secret # 이 블록은 secret 프로필이 활성화시 로드됩니다.
      # application-{name}으로 나누면 name 이라는 프로필을 나눈것과 동일

  datasource:
    url: jdbc:mysql://localhost:3306/web2
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: "XLsJxKSTztZmOcjPj8qQNZpirpiuW3uPTuPeAI/ZkWMRvUGf+yi3VwnrLst8/WMRj1VBKHA0AQ2hYVNubcL8Tw=="
  access-expire-millis: 900000 # 15분 -> ms
  refresh-expire-millis: 86400000 # 1일 1 * 24 * 60 * 60 * 1000